name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '../../src/index.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: mouayad04/typescript-starter:1.0.0
          build-args: |
            NODE_ENV=production
        if: success()

      - name: Verify Docker image
        run: docker run --rm mouayad04/typescript-starter:1.0.0 npm run test
